# Generated by Django 5.1.1 on 2024-10-02 01:41

import apps.menu.models.schedule
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DishType",
            fields=[
                ("_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, default="", max_length=150)),
            ],
            options={
                "db_table": "dish_type",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                ("description", models.TextField(default="")),
            ],
            options={
                "db_table": "menu",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OrderDish",
            fields=[
                ("_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "start_time",
                    models.TimeField(
                        default=apps.menu.models.schedule.default_start_time
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default=apps.menu.models.schedule.default_start_time
                    ),
                ),
                ("date", models.DateField(default=datetime.date(2024, 10, 1))),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dish_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="menu.dishtype",
                    ),
                ),
            ],
            options={
                "db_table": "dish",
            },
        ),
        migrations.CreateModel(
            name="MenuDish",
            fields=[
                ("_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.dish"
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.menu"
                    ),
                ),
            ],
        ),
    ]
