# Generated by Django 5.1.1 on 2024-10-02 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_date",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="date",
            field=models.DateField(default=datetime.date(2024, 10, 2)),
        ),
    ]
