# Generated by Django 5.1.1 on 2024-10-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_remove_order_order_date_alter_schedule_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="dish_type",
        ),
    ]
