# Generated by Django 5.1.1 on 2024-10-03 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_dish_dish_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dish",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="menu.dish"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
