# Generated by Django 5.1.1 on 2024-10-03 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_order_dish_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="date",
        ),
        migrations.AddField(
            model_name="schedule",
            name="day",
            field=models.DateField(default=datetime.date(2024, 10, 3)),
        ),
    ]
