# Generated by Django 5.1.1 on 2024-10-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_remove_schedule_date_schedule_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="day",
            new_name="date",
        ),
    ]
