# Generated by Django 5.1.1 on 2024-10-04 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0008_rename_day_schedule_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menudish",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="date",
            field=models.DateField(default=datetime.date(2024, 10, 4)),
        ),
    ]
