# Generated by Django 5.1.1 on 2024-10-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0009_remove_menudish_quantity_alter_schedule_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderDish",
        ),
    ]
