# Generated by Django 5.1.1 on 2024-10-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_is_super_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="person",
        ),
        migrations.AddField(
            model_name="client",
            name="enterprise",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="username",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="client",
            name="_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
